version: '3.8'
services: 
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      # - 3000:3000
      - 5432:5432
   
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=123456
      - POSTGRESQL_DATABASE=api-anderson